name: Docker publish

on:
  schedule:
    - cron: '45 0 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  packages: read
  actions: read
  security-events: write

jobs:

  gitversion:
    name: Execute GitVersion and create tag
    uses: bvandevliet/Actions.Shared/.github/workflows/git-version.yml@master

  build-push:
    needs: [gitversion]
    name: Build and push
    uses: bvandevliet/Actions.Shared/.github/workflows/docker-build-push.yml@master
    with:
      CR_REGISTRY: docker.io
      IMAGE_NAME: ${{ github.repository_owner }}/duckdns
      majorMinorPatch: ${{ needs.gitversion.outputs.majorMinorPatch }}
      preReleaseLabel: ${{ needs.gitversion.outputs.preReleaseLabel }}
      semVer: ${{ needs.gitversion.outputs.semVer }}
      assemblySemVer: ${{ needs.gitversion.outputs.assemblySemVer }}
      assemblySemFileVer: ${{ needs.gitversion.outputs.assemblySemFileVer }}
    secrets:
      CR_USERNAME: ${{ secrets.CR_USERNAME }}
      CR_PASSWORD: ${{ secrets.CR_PASSWORD }}